[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
glam = "0.30.9"
itertools = "0.14.0"
memoize = "0.5.1"
rayon = "1.11.0"
tokio = { version = "1.48.0", features = ["full", "rt"] }
wgpu = "27.0.1"
z3 = "0.19.5"
